### ISSUE TITLE
Module 'RepeatoRender' not found

### ISSUE THREAD

**Issue by mbuchetics** [stoefln/RepeatoCapture#4]
I tried integration RepeatoCapture into my Xcode project, but it fails with `Module 'RepeatoRender' not found` inside `RepeatoCapture.m`.
I added Repeato using SPM as described in the documentation.

Also, a related question: looking at RepeatoCapture.m I can see that an error is thrown if the package is included in Release builds. Do I need to add a separate target, which is only used for testing or is there another way to have a single target for Release & Debug?

**Comment by stoefln** [comment]
Hi @mbuchetics!
We haven't had the problem you are describing. Can you let me know which version of XCode you are running?

Currently, Repeato iOS is not supposed to be integrated into release builds because apple would reject our library when the app is submitted to the app store. However, this might change in the near future.

**Comment by mbuchetics** [comment]
This was with Xcode 12.5.1, I will try the integration with Xcode 13.1 again and will let you know if that helps. I noticed that sometimes it built without an issue but especially when running a clean build, the error occurred. It may be an SPM issue.

**Comment by stoefln** [comment]
Yes, that would be great @mbuchetics. Thank you!

**Comment by mbuchetics** [comment]
I just tried it out with Xcode 13.1. The error occured once, but after another Clean Build it now seems to work fine. I also did a command line build using Fastlane and that also worked.

**Comment by stoefln** [comment]
Great, thanks for letting us know @mbuchetics
